title: Colos
description: A Jekyll theme
url: http://colos.adrianhaasler.com
email: dev@adrianhaasler.com
permalink: /:categories/:title/
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'with_toc_data']
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md']
include: ['_feeds', '_pages']
locales:
  es:
    description: Un tema para Jekyll
    homeurl: /es
