title: Colos
description: A Jekyll theme
url: http://colos.adrianhaasler.com
email: dev@adrianhaasler.com
permalink: /:categories/:title/
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'with_toc_data']
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md']
include: ['_feeds', '_pages']
defaults:
  -
    scope:
      path: ''
    values:
      layout: default
  -
    scope:
      path: _feeds
    values:
      layout: feed
  -
    scope:
      path: _feeds/en
    values:
      lang: en
  -
    scope:
      path: _pages/en
    values:
      lang: en
  -
    scope:
      path: _posts/en
    values:
      lang: en
  -
    scope:
      path: _feeds/es
    values:
      lang: es
  -
    scope:
      path: _pages/es
    values:
      lang: es
  -
    scope:
      path: _posts/es
    values:
      lang: es
locales:
  en:
    full_lang_name: English
  es:
    full_lang_name: Español
    description: Un tema para Jekyll
    homeurl: /es
